// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW59cksebjXkxE2RTth1-DCIFbgXse-FY',
    appId: '1:388589472841:web:b23ca1bc78ee85778c8398',
    messagingSenderId: '388589472841',
    projectId: 'carepet-b8bd3',
    authDomain: 'carepet-b8bd3.firebaseapp.com',
    databaseURL: 'https://carepet-b8bd3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carepet-b8bd3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljUCCd_ARkmehecPLaGJfq8vs43cJN7I',
    appId: '1:388589472841:android:503183f4ab61a8528c8398',
    messagingSenderId: '388589472841',
    projectId: 'carepet-b8bd3',
    databaseURL: 'https://carepet-b8bd3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carepet-b8bd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3JE0J2AT6am2NmlZ5i43_8JfTZLjoXRE',
    appId: '1:1072306408314:ios:81e2a03fd637b2b0aae4c3',
    messagingSenderId: '1072306408314',
    projectId: 'facediseasesapp-635d0',
    storageBucket: 'facediseasesapp-635d0.appspot.com',
    iosBundleId: 'com.example.faceDiseasesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3JE0J2AT6am2NmlZ5i43_8JfTZLjoXRE',
    appId: '1:1072306408314:ios:e660a19151547bc3aae4c3',
    messagingSenderId: '1072306408314',
    projectId: 'facediseasesapp-635d0',
    storageBucket: 'facediseasesapp-635d0.appspot.com',
    iosBundleId: 'com.example.faceDiseasesApp.RunnerTests',
  );
}