// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW59cksebjXkxE2RTth1-DCIFbgXse-FY',
    appId: '1:388589472841:web:90accbf9282566b38c8398',
    messagingSenderId: '388589472841',
    projectId: 'carepet-b8bd3',
    authDomain: 'carepet-b8bd3.firebaseapp.com',
    databaseURL: 'https://carepet-b8bd3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carepet-b8bd3.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW59cksebjXkxE2RTth1-DCIFbgXse-FY',
    appId: '1:388589472841:web:90accbf9282566b38c8398',
    messagingSenderId: '388589472841',
    projectId: 'carepet-b8bd3',
    authDomain: 'carepet-b8bd3.firebaseapp.com',
    databaseURL: 'https://carepet-b8bd3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carepet-b8bd3.appspot.com',
  );
}
